apiVersion: v1
kind: Service
metadata:
  name: {{ include "gotchiminer.fullname" . }}-server
  labels:
    {{- include "gotchiminer.labels" . | nindent 4 }}
spec:
  type: {{ .Values.server.type }}
  ports:
    - port: {{ .Values.server.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: gotchiminer-server
